name: Data Queen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13867
title: 'Storytelling, Science and Art'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#785261'
    - '#212733'
    - '#c4c6c5'
    - '#ffffff'
    - '#dc664c'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
