name: Data Queen
favicon: null
layout_spectrum: 0.1799
typography_spectrum: 0.93159
title: 'Storytelling, Science and Art'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#110f10'
    - '#f0542e'
    - '#827c86'
    - '#860734'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
