name: Data Queen
favicon: null
layout_spectrum: 0.61877
typography_spectrum: 0.13867
title: 'Storytelling, Science and Art'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0906'
    - '#aba7b8'
    - '#7c575e'
    - '#e26992'
    - '#1d7eb5'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
